In [0]:
import matplotlib

In [0]:
import numpy as np

In [0]:
d = np.array([[2,3,4],[5,6,7],[8,9,10]])

In [15]:
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [43]:
type(d)

numpy.ndarray

In [45]:
d.shape              # it will tell the dimension of array 

(3, 3)

In [16]:
d[0:,0:]   # will print all rows and all columns

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [63]:
d[2,2]

10

In [17]:
d[0:,2]   # print all rows and 2nd column 

array([ 4,  7, 10])

In [20]:
d[0:2]    # print the rows from 0 to no. 2    here 2 reprents no. of totoal row

array([[2, 3, 4],
       [5, 6, 7]])

In [22]:
d[0:,[0,2]]  # print all rows with 0th column and 2nd column

array([[ 2,  4],
       [ 5,  7],
       [ 8, 10]])

In [34]:
d[1:,[1,2]]

array([[ 6,  7],
       [ 9, 10]])

In [37]:
d[[1,2],[1,2]]

array([ 6, 10])

In [38]:
d[1:,1:]

array([[ 6,  7],
       [ 9, 10]])

In [39]:
d[[1,2],1:]

array([[ 6,  7],
       [ 9, 10]])

In [40]:
d[[1,2],2]

array([ 7, 10])

In [42]:
d[[0,2],[0,2]]

array([ 2, 10])

In [0]:
b=np.array([[1,2],[2,3],[4,5]])

In [60]:
b

array([[1, 2],
       [2, 3],
       [4, 5]])

In [61]:
b.shape # no.of rows and no. of columns

(3, 2)

In [62]:
b.reshape(2,3)   #to change the dimension of array

array([[1, 2, 2],
       [3, 4, 5]])

In [64]:
np.full((2,3),5)   # create an array of 2 x 3 dimension and all the elements must be 5

array([[5, 5, 5],
       [5, 5, 5]])

In [0]:
k = np.zeros((2,3))

In [71]:
type(k)

numpy.ndarray

In [0]:
j = np.zeros((2,3),dtype = int)

In [75]:
j

array([[0, 0, 0],
       [0, 0, 0]])

In [76]:
j.dtype

dtype('int64')

In [78]:
np.eye(2,dtype=int)         # to create an Identity matrix

array([[1, 0],
       [0, 1]])

In [84]:
np.random.random((2,3))     # to create array of random elements  

array([[0.88520088, 0.25058311, 0.19438186],
       [0.68872121, 0.86697866, 0.15059538]])

In [85]:
np.arange(10)**2             # create an array of 10 elements with square of each natural number

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [70]:
del numpy                   


NameError: ignored

In [0]:
del np     # to remove numpy module as it creates a lot of space