<a href="https://colab.research.google.com/github/Kritika-30/ML-/blob/Data_processing/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib

In [0]:
import numpy as np

In [0]:
d = np.array([[2,3,4],[5,6,7],[8,9,10]])

In [5]:
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
type(d)

numpy.ndarray

In [7]:
d.shape

(3, 3)

In [8]:
d[0:,0:]   # will print all rows and all columns

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [9]:
d[0:,2]   # print all rows and 2nd column 

array([ 4,  7, 10])

In [10]:
d[0:2]    # print the rows from 0 to no. 2    here 2 reprents no. of totoal row

array([[2, 3, 4],
       [5, 6, 7]])

In [11]:
d[0:,[0,2]]  # print all rows with 0th column and 2nd column

array([[ 2,  4],
       [ 5,  7],
       [ 8, 10]])

In [12]:
d[2,2]

10

In [0]:
d[[1,2],[1,2]]

In [13]:
d[1:,[1,2]]

array([[ 6,  7],
       [ 9, 10]])

In [14]:
d[[1,2],[1,2]]

array([ 6, 10])

In [16]:
d[1:,[1,2]]

array([[ 6,  7],
       [ 9, 10]])

In [17]:
d[1:,1:]

array([[ 6,  7],
       [ 9, 10]])

In [18]:
d[[1,2],2]

array([ 7, 10])

In [0]:
b=np.array([[1,2],[2,3],[4,5]])

In [21]:
b

array([[1, 2],
       [2, 3],
       [4, 5]])

In [23]:
b.shape # no.of rows and no. of columns

(3, 2)

In [24]:
b.reshape(2,3)           #to change the dimension of array

array([[1, 2, 2],
       [3, 4, 5]])

In [25]:
np.full((2,3),5)   # create an array of 2 x 3 dimension and all the elements must be 5

array([[5, 5, 5],
       [5, 5, 5]])

In [0]:
k = np.zeros((2,3))

In [27]:
type(k)

numpy.ndarray

In [0]:
j = np.zeros((2,3),dtype = int)

In [29]:
j

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
j.dtype

dtype('int64')

In [32]:
np.eye(2,dtype=int)   #to create an Identity matrix

array([[1, 0],
       [0, 1]])

In [33]:
np.random.random((2,3))    # to create array of random elements

array([[0.61447042, 0.1011639 , 0.61252704],
       [0.66585586, 0.74991745, 0.07240034]])

In [35]:
np.arange(10)**2        # create an array of 10 elements with square of each natural numbers

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
del numpy


NameError: ignored

In [0]:
del np